theme: jekyll-theme-minimal #jekyll-theme-minimal
title: [Hippolyte Mayard]
subtitle: [Hippolyte Mayard]
author: Hippolyte Mayard
description1: 👨🏼‍💻 Deep Learning engineer @Allisone.ai
description2: 👨🏼‍🎓 MVA - ENS Paris-Saclay
description3: 👨🏼‍🎓 IASD - Université Paris-Dauphine PSL


logo: /assets/images/image.png
simple_search: https://www.google.com/search
url_resume : https://drive.google.com/u/0/uc?id=1NIg3fLeV_SuUJ2s5xOAuAePzozW1GpVN&export=download

header_navigation:
  - title: Home
    url: /index.md

show_downloads: false
google_analytics: false

github: 
  is_user_page: true
  is_project_page: false


markdown: kramdown
kramdown:
  math_engine: mathjax