theme: jekyll-theme-minimal #jekyll-theme-minimal
title: [Hippolyte Mayard]
subtitle: [Hippolyte Mayard]
author: Hippolyte Mayard
description1: 👨🏼‍💻 Deep Learning engineer @Allisone.ai
description2: 👨🏼‍🎓 MVA - ENS Paris-Saclay
description3: 👨🏼‍🎓 IASD - Université Paris-Dauphine PSL


logo: /assets/images/image.png
simple_search: https://www.google.com/search

header_navigation:
  - title: Home
    url: /index.md

show_downloads: false
is_user_page: false
is_project_page: false
google_analytics:

markdown: kramdown
kramdown:
  math_engine: mathjax